version: "3"

services:
    nginx:
        container_name: nginx
        build: 
            context: ./requirement/nginx/
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        restart: always
        depends_on:
            - wordpress
        init: true

    mariadb:
        container_name: mariadb
        build: 
            context: ./requirement/mariadb/
        env_file:
            - ./.env
        ports:
            - "3307:3306"
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        init: true
        restart: always
    
    wordpress:
        container_name: wordpress
        build: 
            context: ./requirement/wordpress/
        ports:
            - "9000:9000"
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        depends_on:
            - mariadb
        init: true
        restart: always


volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress

networks:
    inception: